# Generated by Django 4.1.1 on 2023-07-20 09:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                ("testimony", ckeditor.fields.RichTextField(null=True)),
                ("position", models.CharField(max_length=150)),
                ("picture", models.ImageField(upload_to="testinomy/photos")),
                ("is_published", models.BooleanField(default=False)),
            ],
        ),
    ]
