# Generated by Django 4.1.1 on 2023-08-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Course")),
                ("brief", models.TextField()),
                ("numbers", models.IntegerField()),
                ("is_published", models.BooleanField(default=False)),
            ],
        ),
    ]
