# Generated by Django 4.1.1 on 2023-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonie", "0002_achievement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimony",
            name="picture",
            field=models.ImageField(upload_to="testinony/photos"),
        ),
    ]
