# Generated by Django 4.1.1 on 2023-08-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OurBoard",
            new_name="BoardMember",
        ),
    ]
