# Generated by Django 4.1.1 on 2023-07-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="GetInvolve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=200, verbose_name="Full Name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="Phone Mobile")),
                ("category", models.CharField(max_length=20, verbose_name="")),
            ],
            options={
                "verbose_name_plural": "Involvement Request",
            },
        ),
    ]
