# Generated by Django 5.0 on 2024-02-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='getinvolve',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
