# Generated by Django 5.0 on 2024-02-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('photo', models.ImageField(upload_to='Courses')),
                ('description', models.TextField()),
                ('registration_link', models.URLField(blank=True, max_length=300)),
                ('is_publish', models.BooleanField(default=False)),
            ],
        ),
    ]
